stages:
  - filter_amd64
  - filter_prefix
  - filter_rest

#workflow:
#  rules:
#    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || ($CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH=="master") || $TEST_ALL == "1" || $PROBABILITY

variables:
  REPO_NAME: "apn"

default:
  image: apnpucky/gentoo-apn:latest

.images: &images
  IMAGE:
    [
      apnpucky/gentoo-apn:latest,
#      apnpucky/gentoo-apn-unstable:latest,
    ]

#.filter:
#  stage: filter
#  script:
#    - echo "Filtering $CATEGORY/$PKG/$PKG-$VERSION"
#  rules:
#    - changes:
#        - "$CATEGORY/$PKG/$PKG-$VERSION*.ebuild"
#        - "$CATEGORY/$PKG/metadata.xml"
#        - "$CATEGORY/$PKG/Manifest"
#        - "$CATEGORY/$PKG/files/*"
#        - "$CATEGORY/$PKG/.build"
#        - ".build"


.filter_amd64:
  stage: filter_amd64
  variables:
    IMAGE: apnpucky/gentoo-apn:latest
    PREFIX: ""
  trigger:
    include: base.gitlab-ci.yml
    forward:
      pipeline_variables: true
    strategy: depend
  rules:
    - if: $ARCH == "amd64"
      changes:
        - "$CATEGORY/$PKG/$PKG-$VERSION*.ebuild"
        - "$CATEGORY/$PKG/metadata.xml"
        - "$CATEGORY/$PKG/Manifest"
        - "$CATEGORY/$PKG/files/*"
        - "$CATEGORY/$PKG/.build"
        - ".build"

.filter_prefix:
  stage: filter_rest
  variables:
    IMAGE: apnpucky/debian-gentoo-prefix-ci:latest
    PREFIX: "/gentoo-prefix"
  trigger:
    include: base.gitlab-ci.yml
    forward:
      pipeline_variables: true
    strategy: depend
  rules:
    - if: $ARCH == "amd64"
      changes:
        - "$CATEGORY/$PKG/$PKG-$VERSION*.ebuild"
        - "$CATEGORY/$PKG/metadata.xml"
        - "$CATEGORY/$PKG/Manifest"
        - "$CATEGORY/$PKG/files/*"
        - "$CATEGORY/$PKG/.build"
        - ".build"

.filter_rest:
  stage: filter_rest
  variables:
    IMAGE: apnpucky/gentoo-apn:latest
    PREFIX: ""
  trigger:
    include: base.gitlab-ci.yml
    forward:
      pipeline_variables: true
    strategy: depend
  rules:
    - if: $ARCH != "amd64"
      changes:
        - "$CATEGORY/$PKG/$PKG-$VERSION*.ebuild"
        - "$CATEGORY/$PKG/metadata.xml"
        - "$CATEGORY/$PKG/Manifest"
        - "$CATEGORY/$PKG/files/*"
        - "$CATEGORY/$PKG/.build"
        - ".build"
